### ISSUE TITLE
Request a clear description of how the code works

### ISSUE THREAD

**Issue by swenqing** [meaten/FlowChain-ICCV2023#1]
Dear Author, I am very interested in your recent article, I have some cross background work that I would like to cite your article, so I would like you to elaborate on the flow of your code implementation and give an easy to understand brief description. I would also like you to package it into a stable version that can be called with the "pip install" command. Thank you very much.

**Comment by meaten** [comment]
Hi swenqing,

Thanks for reaching my article.
FlowChain has N normalizing flow modules. N is equal to the future prediction time steps. Each flow module transforms the probability densities of the previous time step to the next one (e.g. t+1 -> t+2). FlowChain is trained to maximize the likelihood of the ground truth on all future time steps. We propose the ultra-fast update of prediction, which reuses the probability change ( log-det-jacobian by flow modules ) in the next time step to skip the verbose computation.

PIP packaging can take several months because I am currently working on code cleaning and extension for the next publication.
I definitely will consider your request for packaging.

**Comment by meaten** [comment]
If you need further explanation, feel free to re-open this issue!
